### ISSUE TITLE
Quick bookmark shortcut

### ISSUE THREAD

**Issue by Orriky** [teddy-gustiaux/default-bookmark-folder#216] opened 2020-04-23 05:25 UTC
# This is a Bug Report

## Description
Quick bookmark shortcut once enabled doesn't work anymore after a Firefox restart

## Specifications

- Version of the add-on: 2.12.1
- Firefox edition: Firefox  Developer Edition
- Firefox version: 76.0b7 (64 bit)
- Firefox language: Italian
- Platform/OS: Windows 8.1 Pro (64 bit)

**Comment by teddy-gustiaux** [comment] 2024-02-05 01:18
Considering the age of the original report, and that I am not able to reproduce the issue, I am going to close this. It can be re-opened as needed if further information to help reproducing the issue is provided.

**Closed by teddy-gustiaux** 2024-02-05 01:18 UTC
Labels: type/bug
