### ISSUE TITLE
ALT+SHIFT+D conflicts with German File menu

### ISSUE THREAD

**Issue by jmozmoz** [teddy-gustiaux/default-bookmark-folder#6] opened 2017-12-13 00:09 UTC
When pressing ALT+SHIFT+D Firefox opens the file menu in the German version (ATL+D opens the menu, SHIFT is ignored). The current page is not bookmarked. 

Please, either change the short cut to a locale specific value or make it user configurable.

**Comment by teddy-gustiaux** [comment] 2017-12-23 21:13
I have been able to reproduce this bug with the German language pack installed. Unfortunately, it is not possible (according the API [documentation](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/commands)) to change the shortcut depending on the locale.

There are a few options to solve this problem:

1. One option is to add a second shortcut that would work with the German interface.

2. Another solution (that would make the add-on require more permissions) would be to inject JavaScript on each page to be able to properly listen to the shortcuts and overriding them if necessary (like in this case), as Firefox does not allow this at the moment.

3. Lastly, making the shortcut user configurable. That would requires the same as the previous option, and more work to be able to handle all the possibilities properly.

One of the features I was hoping to introduce in the future was the possibility of overriding the built-in Ctrl+D shortcut to quick bookmark the page, so I am going to investigate option n°2 at the moment.

**Comment by teddy-gustiaux** [comment] 2018-04-19 00:41
Firefox 60 will introduce new API that might allow to fix this in a clean way, as mentioned in this [blog post.](https://blog.mozilla.org/addons/2018/04/02/extensions-firefox-60/).

> Dynamic Keyboard Shortcuts
> 
> Two new API were added to the Commands namespace that allow extensions to change their keyboard shortcuts at runtime. The first, commands.update, allows an extension to change the shortcut key and/or description associated with a command, while the second, commands.reset, reverts a command back to the keyboard shortcut and description originally specified in the manifest file.

**Comment by teddy-gustiaux** [comment] 2018-07-03 20:30
Some updates: I have tested the [new ](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/commands/update) [API ](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/commands/reset) mentioned previously. It does indeed allow the user to configure a shortcut and works well _as long as the shortcut set up is not already used by Firefox_.

It is an intended behavior of Firefox for security reasons (at least for the moment). [This bug on Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1320332) as well as [this one](https://bugzilla.mozilla.org/show_bug.cgi?id=1215061#c60) asks for better support of user-configurable shortcut, but wait and see for the moment.

So, I think I will try and add the option of configuring the shortcut of the quick bookmarking in the future major version, and I will also include some details regarding this problem. Hopefully one day any shortcut will be able to be used.

**Comment by teddy-gustiaux** [comment] 2018-07-06 21:19
[Another interesting improvement](https://bugzilla.mozilla.org/show_bug.cgi?id=1364784), which should help providing a wider selection of shortcut choice for the users. Planned so far for Firefox 63 (which will be released in October according to the [release calendar](https://wiki.mozilla.org/Release_Management/Calendar)).

**Comment by teddy-gustiaux** [comment] 2019-03-31 23:56
With the release of [version](https://www.mozilla.org/en-US/firefox/66.0/releasenotes/) [66](https://hacks.mozilla.org/2019/03/firefox-66-the-sound-of-silence/), it is now possible to [manage extension shortcuts in Firefox](https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox). 🎉
This new feature solves the problem originally described by the issue. Therefore, I have decided to close it. For more details, please read below.

---

I understand the default quick bookmarking shortcut is not suitable for everyone, and I doubt one that could satisfy all users can be found. So, the default shortcut will remain the same (Alt+Shift+D).

I also understand the problem will remain for users using an earlier version of Firefox and not able to upgrade. However, this issue has been open for over a year without any significant improvements (because of both technical limitations and time reasons). With this new feature available, I do not see myself having the time or the motivation to code something already natively available in Firefox.

If someone is willing to do the work and submit a pull request, I will happily merge it! For any other bug, feature request or question, please feel free to open a new issue.

Thanks for your understanding, and happy browsing! 🙂

**Closed by teddy-gustiaux** 2019-03-31 23:56 UTC
Labels: type/bug, type/enhancement
