### ISSUE TITLE
Can't Select Any Folders to Use as Default Folder

### ISSUE THREAD

**Issue by maep1** [teddy-gustiaux/default-bookmark-folder#24] opened 2018-06-15 21:50 UTC
Hello, everything installed fine, but when I click Options it says "Select where new bookmarks will be added" along with a drop-down lists however, the only "option" that is offered is "use Firefox's default bookmark location." No other folders are shown. The same for the Bookmark All tabs. There's nothing else to click. Please advise. Thank you.

**Comment by teddy-gustiaux** [comment] 2018-06-19 00:20
Hello! Thanks for reporting this issue. The drop-down lists should be populated with the list of bookmark folders, so something is indeed not working properly. I will need more information in order to try and figure out exactly what is happening. Which version of Firefox are you using?

**Comment by maep1** [comment] 2018-06-25 12:30
Hello,

 

Sorry for the late reply, I just saw this message in my folder.

 

This add-on was working fine, then suddenly there was nothing in the drop-down folders.

 

I am using Firefox version 56. The newer versions don’t allow the New Tabs add-on (and I don’t prefer them overall), but all of my other add-ons work fine (about 4 total).


Thank you.

 

Mae

**Comment by teddy-gustiaux** [comment] 2018-06-25 21:14
No problem, thank you for the information! 

I have installed the add-on in Firefox 56.0, 56.0.1 and 56.0.2 (both 32 and 64 bits), and I was unfortunately unable to reproduce the problem. Which version of the add-on are you currently using? It should be the latest one (`2.4.0`) but I prefer to check.

I don't know how familiar you are with _Firefox profiles_, but something you can try is creating a new clean profile, install the add-on and check if the problem is still present.

More information on profiles are available here:

- [Profiles - Where Firefox stores your bookmarks, passwords and other user data](https://support.mozilla.org/en-US/kb/profiles-where-firefox-stores-user-data)
- [Use the Profile Manager to create and remove Firefox profiles](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles)

**Comment by maep1** [comment] 2018-06-28 00:11
Thank you, it is 2.4.0. I am very familiar with profiles so I will try creating a new one and see if it works and then import my old profile into that. I’ll let you know how it turns out. 

 

Thanks again!

**Comment by teddy-gustiaux** [comment] 2018-06-28 01:30
That sounds great! 👍 I look forward to hearing back from you, hopefully with good news! 😄

**Comment by teddy-gustiaux** [comment] 2018-09-08 00:16
Since it has been more than two months without any update, I am closing the issue. Feel free to reopen it if need be!

**Closed by teddy-gustiaux** 2018-09-08 00:16 UTC
